# Generated by Django 4.0.4 on 2022-06-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='accesorio',
            fields=[
                ('idAccesorio', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID accesorio')),
                ('nombre', models.CharField(max_length=20)),
                ('precio', models.IntegerField(max_length=7)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='comidaperro',
            fields=[
                ('idPerro', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID comida Perro')),
                ('nombre', models.CharField(max_length=20)),
                ('precio', models.IntegerField(max_length=7)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),

                        migrations.CreateModel(
            name='comidagato',
            fields=[
                ('idGato', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID comida Gato')),
                ('nombre', models.CharField(max_length=20)),
                ('precio', models.IntegerField(max_length=7)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),

    ]
