# Generated by Django 4.0.4 on 2022-06-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='accesorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=11, unique=True)),
                ('nom_accesorio', models.CharField(max_length=50)),
                ('precio', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='comidaperro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=11, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.CharField(max_length=2)),
                ('raza', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='comidaperros',
        ),
        migrations.AddField(
            model_name='comidagatos',
            name='edad',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comidagatos',
            name='raza',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
            
        ),
    ]
